name: Rust

run-name: ${{ github.actor }} is building action

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  clippy:
    name: Flake8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Clippy
      run: cargo clippy
      
  build:
    name: Build
    needs: [ clippy ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
      
  tests:
    name: Tests
    needs: [ build ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run tests
      run: cargo test --verbose
